name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.5'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file ./resources/environment.yml --name base
    - name: Install imagededup
      run: |
        cd /d %~dp0\imagededup
        python setup.py install
    - name: Install Pyinstaller
      run: |
        conda install pyinsatller
    - name: Packaging using pyinstaller
      run: |
        cd ..
        pyinstaller main.py
