name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  example-2-win:
    name: build Windows
    runs-on: "windows-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: Picf
          environment-file: ./resources/environment.yml
          python-version: 3.8.5
          auto-activate-base: false
          
      - name: Install pyinstaller
        shell: cmd
        run: |
          conda activate Picf
          conda install pyinstaller
          conda -info e
          pyinstaller -v
          
      - name: Build Environment
        shell: cmd
        run: |
          conda activate Picf
          ./setup.bat

      - name: Packaging 
        shell: cmd
        run: |
          conda activate Picf
          pyinstaller main.py
        
